/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    enquiries: Enquiry;
    courses: Course;
    'service-categories': ServiceCategory;
    packages: Package;
    gallery: Gallery;
    reviews: Review;
    'success-stories': SuccessStory;
    faqs: Faq;
    media: Media;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    enquiries: EnquiriesSelect<false> | EnquiriesSelect<true>;
    courses: CoursesSelect<false> | CoursesSelect<true>;
    'service-categories': ServiceCategoriesSelect<false> | ServiceCategoriesSelect<true>;
    packages: PackagesSelect<false> | PackagesSelect<true>;
    gallery: GallerySelect<false> | GallerySelect<true>;
    reviews: ReviewsSelect<false> | ReviewsSelect<true>;
    'success-stories': SuccessStoriesSelect<false> | SuccessStoriesSelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    'site-photos': SitePhoto;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'site-photos': SitePhotosSelect<false> | SitePhotosSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Every enquiry sent from the website forms. Update the status as you follow up.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enquiries".
 */
export interface Enquiry {
  id: number;
  name: string;
  /**
   * 10-digit Indian mobile number
   */
  phone: string;
  email?: string | null;
  course?: string | null;
  message?: string | null;
  status?: ('new' | 'contacted' | 'demo' | 'enrolled' | 'closed') | null;
  /**
   * Internal notes (not visible to the student).
   */
  notes?: string | null;
  consent?: boolean | null;
  sourcePage?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courses".
 */
export interface Course {
  id: number;
  title: string;
  /**
   * Used in the web address, e.g. "bridal" → /courses/bridal
   */
  slug: string;
  /**
   * Lower numbers show first.
   */
  order?: number | null;
  level: 'beginner' | 'advanced' | 'short';
  image?: (number | null) | Media;
  /**
   * One or two sentences shown under the title.
   */
  blurb: string;
  duration?: string | null;
  batches?: string | null;
  /**
   * e.g. "₹15,000 (instalments available)"
   */
  fees?: string | null;
  highlights?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  whoFor?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  modules?:
    | {
        title: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Paste the code after /reel/ in an Instagram reel link.
   */
  reels?:
    | {
        code: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Photos used across the website, plus the course brochure (PDF).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Short description of the photo, for screen readers and Google.
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    thumb?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Salon services, grouped by category (Bridal, Hair, Nails…).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "service-categories".
 */
export interface ServiceCategory {
  id: number;
  name: string;
  slug: string;
  order?: number | null;
  icon?:
    | (
        | 'crown'
        | 'scissors'
        | 'drop'
        | 'spark'
        | 'hand'
        | 'gem'
        | 'flower'
        | 'brush'
        | 'award'
        | 'brief'
        | 'heart'
        | 'cal'
        | 'users'
        | 'sofa'
        | 'img'
        | 'play'
        | 'ig'
        | 'star'
        | 'pin'
        | 'clock'
      )
    | null;
  /**
   * Banner photo for this category. Use a photo that shows this service.
   */
  image?: (number | null) | Media;
  /**
   * Which part of the photo stays visible in the banner crop.
   */
  imagePosition?: ('top' | 'center') | null;
  blurb: string;
  items?:
    | {
        name: string;
        /**
         * Short description
         */
        note?: string | null;
        /**
         * Optional, e.g. "₹2,500" or "from ₹999"
         */
        price?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "packages".
 */
export interface Package {
  id: number;
  name: string;
  order?: number | null;
  icon?:
    | (
        | 'crown'
        | 'scissors'
        | 'drop'
        | 'spark'
        | 'hand'
        | 'gem'
        | 'flower'
        | 'brush'
        | 'award'
        | 'brief'
        | 'heart'
        | 'cal'
        | 'users'
        | 'sofa'
        | 'img'
        | 'play'
        | 'ig'
        | 'star'
        | 'pin'
        | 'clock'
      )
    | null;
  /**
   * Optional label such as "Signature". Tagged packages are highlighted.
   */
  tag?: string | null;
  /**
   * Optional, e.g. "from ₹14,999"
   */
  price?: string | null;
  items?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Student portfolio. Only show real work by the academy and its students.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery".
 */
export interface Gallery {
  id: number;
  title: string;
  category: 'bridal' | 'party' | 'hair' | 'nails' | 'classroom' | 'certification';
  /**
   * Leave empty to show a placeholder slot.
   */
  image?: (number | null) | Media;
  /**
   * Course linked from the enlarged photo.
   */
  course?: (number | null) | Course;
  /**
   * Optional, e.g. student name.
   */
  credit?: string | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Real reviews only, e.g. copied from Google with the reviewer's name as shown there.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews".
 */
export interface Review {
  id: number;
  name: string;
  /**
   * Course or service they took.
   */
  course?: string | null;
  quote: string;
  rating?: number | null;
  source?: ('google' | 'direct') | null;
  published?: boolean | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Alumni who started working or opened a salon. Shown on the Reviews page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "success-stories".
 */
export interface SuccessStory {
  id: number;
  name: string;
  /**
   * e.g. "Now runs her own salon in Gohana"
   */
  outcome: string;
  course?: string | null;
  photo?: (number | null) | Media;
  /**
   * Optional YouTube or Instagram link.
   */
  videoUrl?: string | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: number;
  question: string;
  answer: string;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'enquiries';
        value: number | Enquiry;
      } | null)
    | ({
        relationTo: 'courses';
        value: number | Course;
      } | null)
    | ({
        relationTo: 'service-categories';
        value: number | ServiceCategory;
      } | null)
    | ({
        relationTo: 'packages';
        value: number | Package;
      } | null)
    | ({
        relationTo: 'gallery';
        value: number | Gallery;
      } | null)
    | ({
        relationTo: 'reviews';
        value: number | Review;
      } | null)
    | ({
        relationTo: 'success-stories';
        value: number | SuccessStory;
      } | null)
    | ({
        relationTo: 'faqs';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enquiries_select".
 */
export interface EnquiriesSelect<T extends boolean = true> {
  name?: T;
  phone?: T;
  email?: T;
  course?: T;
  message?: T;
  status?: T;
  notes?: T;
  consent?: T;
  sourcePage?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courses_select".
 */
export interface CoursesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  order?: T;
  level?: T;
  image?: T;
  blurb?: T;
  duration?: T;
  batches?: T;
  fees?: T;
  highlights?:
    | T
    | {
        text?: T;
        id?: T;
      };
  whoFor?:
    | T
    | {
        text?: T;
        id?: T;
      };
  modules?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  reels?:
    | T
    | {
        code?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "service-categories_select".
 */
export interface ServiceCategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  order?: T;
  icon?: T;
  image?: T;
  imagePosition?: T;
  blurb?: T;
  items?:
    | T
    | {
        name?: T;
        note?: T;
        price?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "packages_select".
 */
export interface PackagesSelect<T extends boolean = true> {
  name?: T;
  order?: T;
  icon?: T;
  tag?: T;
  price?: T;
  items?:
    | T
    | {
        text?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery_select".
 */
export interface GallerySelect<T extends boolean = true> {
  title?: T;
  category?: T;
  image?: T;
  course?: T;
  credit?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews_select".
 */
export interface ReviewsSelect<T extends boolean = true> {
  name?: T;
  course?: T;
  quote?: T;
  rating?: T;
  source?: T;
  published?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "success-stories_select".
 */
export interface SuccessStoriesSelect<T extends boolean = true> {
  name?: T;
  outcome?: T;
  course?: T;
  photo?: T;
  videoUrl?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        thumb?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  contact?: {
    /**
     * As shown on the site
     */
    phoneDisplay?: string | null;
    /**
     * For tap-to-call, no spaces
     */
    phoneTel?: string | null;
    /**
     * Country code + number, no + or spaces
     */
    whatsapp?: string | null;
    email?: string | null;
    address?: string | null;
    hours?: string | null;
  };
  links?: {
    instagram?: string | null;
    instagramHandle?: string | null;
    youtube?: string | null;
    /**
     * Google Business Profile link
     */
    googleProfile?: string | null;
    /**
     * "Ask for review" short link from the Google profile
     */
    googleReviewLink?: string | null;
    directions?: string | null;
    mapEmbed?: string | null;
  };
  /**
   * Copy from the Google Business Profile. Leave empty to hide.
   */
  rating?: {
    score?: number | null;
    count?: number | null;
  };
  /**
   * Scrolling messages at the very top of every page.
   */
  announcements?:
    | {
        text: string;
        /**
         * e.g. /contact or tel:+91…
         */
        link?: string | null;
        id?: string | null;
      }[]
    | null;
  stats?: {
    instagramFollowers?: number | null;
    postsShared?: number | null;
  };
  /**
   * Code after /reel/ in the Instagram link. The first 6 show on the homepage, all show in the gallery.
   */
  reels?:
    | {
        code: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Course brochure PDF for the "Download Brochure" button.
   */
  brochure?: (number | null) | Media;
  notifications?: {
    /**
     * Where new enquiry emails are sent. Separate several addresses with commas.
     */
    enquiryEmail?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Photos used in fixed places on the website. Empty spots fall back to the built-in photos.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-photos".
 */
export interface SitePhoto {
  id: number;
  /**
   * Square photo of Poonam Mehla, face centred.
   */
  founderPortrait?: (number | null) | Media;
  heroBridal?: (number | null) | Media;
  founderStudio?: (number | null) | Media;
  founderClass?: (number | null) | Media;
  /**
   * Up to 5 bridal looks. The first one is shown larger.
   */
  bridalPortfolio?:
    | {
        image?: (number | null) | Media;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  aboutStory?: (number | null) | Media;
  /**
   * 5 photos of the studio. The first is shown large.
   */
  studioTour?:
    | {
        image?: (number | null) | Media;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * 2 photos: the large arch photo, then the small tilted card (e.g. the studio).
   */
  servicesCollage?:
    | {
        image?: (number | null) | Media;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  bridalBanner?: (number | null) | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  contact?:
    | T
    | {
        phoneDisplay?: T;
        phoneTel?: T;
        whatsapp?: T;
        email?: T;
        address?: T;
        hours?: T;
      };
  links?:
    | T
    | {
        instagram?: T;
        instagramHandle?: T;
        youtube?: T;
        googleProfile?: T;
        googleReviewLink?: T;
        directions?: T;
        mapEmbed?: T;
      };
  rating?:
    | T
    | {
        score?: T;
        count?: T;
      };
  announcements?:
    | T
    | {
        text?: T;
        link?: T;
        id?: T;
      };
  stats?:
    | T
    | {
        instagramFollowers?: T;
        postsShared?: T;
      };
  reels?:
    | T
    | {
        code?: T;
        id?: T;
      };
  brochure?: T;
  notifications?:
    | T
    | {
        enquiryEmail?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-photos_select".
 */
export interface SitePhotosSelect<T extends boolean = true> {
  founderPortrait?: T;
  heroBridal?: T;
  founderStudio?: T;
  founderClass?: T;
  bridalPortfolio?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  aboutStory?: T;
  studioTour?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  servicesCollage?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  bridalBanner?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}